version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./
    ports:
      - "8080:3000"
    networks:
      - app-network
    environment:
      - PORT=3000

networks:
  app-network:
    driver: bridge
